import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <img style={{ width: '100vw', height: '100vh', position: 'fixed', zIndex: '-1', top: '0px', left: '0px' }} alt="pb" src={'/img/bg.jpg'} />
        <div className="container">
          {children}
        </div>
      </body>
    </html>
  );
}
